# Generated by Django 2.1.5 on 2019-03-26 00:01

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190325_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('short_name', models.CharField(blank=True, max_length=25, null=True)),
                ('dept_code', models.CharField(blank=True, max_length=25, null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2019, 3, 26, 0, 1, 49, 502264, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_token', models.CharField(default='pbkdf2:sha256:50000$YnjlTwVs$e9c0a7331435fc0c372224e37a1d1a78e9f5e69e2c4a8e8c03ee713ea1f8c9a3', max_length=1000)),
                ('email_confirmed', models.IntegerField(default=0)),
                ('employee_id', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Rather not say', 'Rather not say')], max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('Married', 'Married'), ('Single', 'Single'), ('Other', 'Other'), ('Rather not say', 'Rather not say')], max_length=20, null=True)),
                ('city', models.CharField(blank=True, choices=[('Accra', 'Accra'), ('Dodowa', 'Dodowa'), ('Oyibi', 'Oyibi'), ('Adenta', 'Adenta')], max_length=20, null=True)),
                ('country', models.CharField(choices=[('Algeria', 'Algeria'), ('Angola', 'Angola'), ('Benin', 'Benin'), ('Botswana', 'Botswana'), ('British Indian Ocean Territory', 'British Indian Ocean Territory'), ('Burkina Faso', 'Burkina Faso'), ('Burundi', 'Burundi'), ('Cameroon', 'Cameroon'), ('Cabo Verde', 'Cabo Verde'), ('Central African Republic', 'Central African Republic'), ('Chad', 'Chad'), ('Comoros', 'Comoros'), ('Congo', 'Congo'), ('Congo (Democratic Republic of the)', 'Congo (Democratic Republic of the)'), ('Djibouti', 'Djibouti'), ('Egypt', 'Egypt'), ('Equatorial Guinea', 'Equatorial Guinea'), ('Eritrea', 'Eritrea'), ('Ethiopia', 'Ethiopia'), ('French Southern Territories', 'French Southern Territories'), ('Gabon', 'Gabon'), ('Gambia', 'Gambia'), ('Ghana', 'Ghana'), ('Guinea', 'Guinea'), ('Guinea-Bissau', 'Guinea-Bissau'), ("Côte d'Ivoire", "Côte d'Ivoire"), ('Kenya', 'Kenya'), ('Lesotho', 'Lesotho'), ('Liberia', 'Liberia'), ('Libya', 'Libya'), ('Madagascar', 'Madagascar'), ('Malawi', 'Malawi'), ('Mali', 'Mali'), ('Mauritania', 'Mauritania'), ('Mauritius', 'Mauritius'), ('Mayotte', 'Mayotte'), ('Morocco', 'Morocco'), ('Mozambique', 'Mozambique'), ('Namibia', 'Namibia'), ('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('Réunion', 'Réunion'), ('Rwanda', 'Rwanda'), ('Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha'), ('Sao Tome and Principe', 'Sao Tome and Principe'), ('Senegal', 'Senegal'), ('Seychelles', 'Seychelles'), ('Sierra Leone', 'Sierra Leone'), ('Somalia', 'Somalia'), ('South Africa', 'South Africa'), ('South Sudan', 'South Sudan'), ('Sudan', 'Sudan'), ('Swaziland', 'Swaziland'), ('Tanzania, United Republic of', 'Tanzania, United Republic of'), ('Togo', 'Togo'), ('Tunisia', 'Tunisia'), ('Uganda', 'Uganda'), ('Western Sahara', 'Western Sahara'), ('Zambia', 'Zambia'), ('Zimbabwe', 'Zimbabwe')], default='GHA', max_length=20)),
                ('country_code', models.CharField(choices=[('213', 'ALG'), ('244', 'ANG'), ('229', 'BEN'), ('267', 'BOT'), ('246', ''), ('226', 'BUR'), ('257', 'BDI'), ('237', 'CMR'), ('238', 'CPV'), ('236', 'CAF'), ('235', 'CHA'), ('269', 'COM'), ('242', 'CGO'), ('243', 'COD'), ('253', 'DJI'), ('20', 'EGY'), ('240', 'GEQ'), ('291', 'ERI'), ('251', 'ETH'), ('', ''), ('241', 'GAB'), ('220', 'GAM'), ('233', 'GHA'), ('224', 'GUI'), ('245', 'GBS'), ('225', 'CIV'), ('254', 'KEN'), ('266', 'LES'), ('231', 'LBR'), ('218', 'LBA'), ('261', 'MAD'), ('265', 'MAW'), ('223', 'MLI'), ('222', 'MTN'), ('230', 'MRI'), ('262', ''), ('212', 'MAR'), ('258', 'MOZ'), ('264', 'NAM'), ('227', 'NIG'), ('234', 'NGR'), ('262', ''), ('250', 'RWA'), ('290', None), ('239', 'STP'), ('221', 'SEN'), ('248', 'SEY'), ('232', 'SLE'), ('252', 'SOM'), ('27', 'RSA'), ('211', ''), ('249', 'SUD'), ('268', 'SWZ'), ('255', 'TAN'), ('228', 'TOG'), ('216', 'TUN'), ('256', 'UGA'), ('212', ''), ('260', 'ZAM'), ('263', 'ZIM')], default='GHA', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=9, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Employee',
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminRemark', models.TextField(blank=True, null=True)),
                ('adminRemarkDate', models.DateTimeField(default=datetime.datetime(2019, 3, 26, 0, 1, 49, 651167, tzinfo=utc), null=True)),
                ('isRead', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('fromDate', models.DateTimeField(default=datetime.datetime(2019, 3, 26, 0, 1, 49, 651244, tzinfo=utc), null=True)),
                ('toDate', models.DateTimeField(default=datetime.datetime(2019, 3, 26, 0, 1, 49, 651274, tzinfo=utc), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavetype', models.CharField(blank=True, max_length=250, null=True)),
                ('creationDate', models.DateTimeField(default=datetime.datetime(2019, 3, 26, 0, 1, 49, 650663, tzinfo=utc), null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='reg_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 0, 1, 49, 503012, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 0, 1, 49, 503077, tzinfo=utc)),
        ),
    ]
