# Generated by Django 2.1.5 on 2019-03-27 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190327_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 15, 30, 39, 28094, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reg_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 15, 30, 39, 28019, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='department',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 15, 30, 39, 27273, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$iwHxIjmQ$ff7539344ba16c23354eed601257eb07ac1134b6c9b1c04a3fa395e9088397ff', max_length=1000),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='adminRemarkDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 15, 30, 39, 109060, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='fromDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 15, 30, 39, 109223, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='postingDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 15, 30, 39, 109256, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Disapproved', 'Disapproved')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='toDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 15, 30, 39, 109285, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 15, 30, 39, 108446, tzinfo=utc), null=True),
        ),
    ]
