# Generated by Django 2.1.5 on 2019-03-27 09:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190327_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_img',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='leaves',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leaves',
            name='leavetype',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 9, 10, 0, 894713, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reg_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 9, 10, 0, 894645, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='department',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 9, 10, 0, 893934, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$QBGPJbKe$91ad86a5cc6fed236a144bf4bb09794bf02433e11eb4ba01e99ec309e6cdd947', max_length=1000),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='adminRemarkDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 9, 10, 0, 973841, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2019, 3, 27, 9, 10, 0, 973914, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='postingDate',
            field=models.DateField(default=datetime.datetime(2019, 3, 27, 9, 10, 0, 973957, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2019, 3, 27, 9, 10, 0, 973983, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 9, 10, 0, 973366, tzinfo=utc), null=True),
        ),
    ]
